{
    'name': 'CRM Lead Days in Work',
    'version': '1.0',
    'category': 'Uncategorized',
    'summary': 'Adding the Days in Work field to CRM leads.',
    'depends': ['crm', 'web'],
    'data': ['views/crm_lead_views.xml',
             "views/customer_credit_views.xml",
             "report/partner_report.xml",
             "report/partner_report_template.xml",
             'wizard/views/client_risk_wizard_views.xml',
             'security/ir.model.access.csv',
             ],
    'installable': True,
    'application': True,
}